<a href="https://colab.research.google.com/github/BrunoRGutierrez/CA-Fluid-Simulation/blob/master/MinimumGlobalCut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
#Insert a valid adjacejcy matrix (from a simple undirected connected graph)
M = np.matrix([[0,1,1],[1,0,1],[1,1,0]])

In [0]:
def elegible_edges(M):
  #Add all edges to a list R
  n = len(M) #range of the matrix
  R = []
  for i in range(n-1):
    for j in range(i+1,n):
      #print([i,j])
      if M[i,j] > 0:
        R.append([i,j])
        #print(R)
  return R 

#edges_list = elegible_edges(M)
#print(edges_list)

In [0]:
import random

def random_edge(list_edges):
  #select without replacement a random edge form de list
  r_edge = random.choice(list_edges)
  #list_edges.remove(r_edge)
  return r_edge, list_edges

#r_edge, edges_list = random_edge(list_edges)
#print(r_edge)
#print(list_edges)

In [0]:
#n = len(M)
#nodes_list = [[i] for i in range(n)]
#nodes_list[0].append(8)
#print(nodes_list) 

def merge_nodes(edge, nodes_list,n):
  #Giving a (i,j) edge, we merge the nodes_list[i],nodes_list[j] into the minimum of both and clear the other one.
  for i in range(n):
    if edge[0] in nodes_list[i]:
      for j in range(i+1,n):
        if edge[1] in nodes_list[j]:
          nodes_list[i].extend(nodes_list[j])
          nodes_list[j].clear()
          nodes_list[i].sort()
          #print('merge function ', nodes_list[i])
          break
      break
          #print(nodes_list[i])
          #print(nodes_list)
    else:
      if edge[1] in nodes_list[i]:
        for j in range(i+1,n):
          if edge[0] in nodes_list[j]:
            nodes_list[i].extend(nodes_list[j])
            nodes_list[j].clear()
            nodes_list[i].sort()
            #print('merge function ', nodes_list[i])
            break
        break
  return nodes_list, i


#nodes_list, big_node = merge_nodes(r_edge,nodes_list)
#print(nodes_list)
#print(big_node)

In [0]:
import itertools


def remove_edges(nodes_list,big_node,edges_list,M):
  #delete all the edges betwen the nodes of the new big node
  #print(nodes_list[big_node])
  #print(list_edges)
  for pair in itertools.combinations(nodes_list[big_node], 2):
    #print(pair)
    if M[pair] >0:
      i,j = pair
      #print('paso el pair ', pair)
      #print(M[pair])
      M[pair] = 0
      M[j,i] = 0
      #print(M[pair])
      edges_list.remove([i,j])
  return edges_list,M




#edges_list,M = remove_edges(nodes_list,big_node,list_edges,M)
#print(edges_list)
#print(M)

In [0]:
def MinimumGlobalCut(M):
  #Input: An adyacence matrix of a simple conected graph, n > 1.
  #Output: An adyacence matrix of a graph that show the minimum global cut with probability at least 2/(n(n − 1)) 
  n = len(M)
  edges_list = elegible_edges(M)
  #print(edges_list) 
  nodes_list = [[i] for i in range(n)]
  #print(nodes_list)
  for k in range(n-2):
    r_edge, edges_list = random_edge(edges_list)
    #print('r_edge', r_edge)
    nodes_list, big_node = merge_nodes(r_edge,nodes_list,n)
    #print(nodes_list)
    #print(big_node)
    edges_list,M = remove_edges(nodes_list,big_node,edges_list,M)
    #print(edges_list)
    #print(M)
  return M, edges_list


In [0]:
#Instert a valid adyacence matrix
M = np.matrix([[0,1,1,1,1,1,1,1,1],
               [1,0,1,1,1,1,1,1,1],
               [1,1,0,1,1,1,1,1,1],
               [1,1,1,0,1,1,1,1,1],
               [1,1,1,1,0,1,1,1,1],
               [1,1,1,1,1,0,1,1,1],
               [1,1,1,1,1,1,0,1,1],
               [1,1,1,1,1,1,1,0,1],
               [1,1,1,1,1,1,1,1,0]])

In [0]:
#Ejecut the algorithm
n = len(M)
M, edges_list = MinimumGlobalCut(M)
print(M)
p = 2/(n*(n-1))
print('Those are the edges of a min cut set with probability at least', p,':')
print(edges_list)

[[0 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]]
Those are the edges of a min cut set with probability at least 0.027777777777777776 :
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8]]
